apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage
  labels:
    app: fil-rouge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
  template:
    metadata:
      labels:
        app: productpage
    spec:
      containers:
      - name: productpage
        image: localhost:5000/productpage:latest
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: service-productpage
spec:
  selector:
    app: productpage
  type: NodePort
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080