apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-v2
  labels:
    app: fil-rouge
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
      - name: ratings
        image: ratings:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE_VERSION
          value: v2
        - name: DB_TYPE
          value: mysql
        - name: MYSQL_DB_HOST
          value: mysql
        - name: MYSQL_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-root-pwd
              key: username
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pwd
              key: password
        ports:
        - containerPort: 9080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-v1
  labels:
    app: fil-rouge
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
        - name: ratings
          imagePullPolicy: IfNotPresent
          image: ratings:latest
          ports:
            - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: ratings
spec:
  selector:
    app: ratings
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080